@abstract class_name ActionVerb extends ActionPart
@abstract func execute() -> void
@abstract func cancel() -> void
@abstract func abort() -> void
@abstract func validate() -> bool
@abstract func update() -> void
@abstract func prepare() -> bool
@abstract func get_distance() -> float
@abstract func serialize() -> String
